### ISSUE TITLE
Special characters in query resulting in 500 internal server error

### ISSUE THREAD

**Issue by Jdruwe** [adobe/commerce-cif-graphql-client#21]
### Expected Behaviour

Magento instance to return an empty 200 response

### Actual Behaviour

java.lang.RuntimeException: GraphQL query failed with response code 500

### Reproduce Scenario (including but not limited to)

We have certain product page urls users can navigate to, Behind the scenes the product code is extracted from the url and used within the graphql query. We have this weird edge case we would like to cover where a user uses special characters in the product code for some reason, for example this url: https://site.com/en-us/p/046677é464486

Behind the scenes we use the 046677é464486 as product code in the query, it looks like this:

```
{
  products(filter: {ctn: {match: "046677é464486"}}) {
    items {
       ...
```

At the moment when we execute a call with this query using the client provided by commerce-cif-graphql-client we get a 500 internal server error returned. When we use the same query and execute it using Postman or even ChromeiQL we get a valid 200 response with no data:

```
{
  "data": {
    "products": {
      "items": []
    }
  }
}
```

For testing purpose I've created a local https endpoint to see what the post body actually looks like:

Postman body:

```
{"query":"{products(filter:{ctn:{match:\"046677é464486\"}}) ...
```

AEM call using GraphqlClientImpl: 

```
{"query":"{products(filter:{ctn:{match:\"046677�464486\"}}) ...
```

Difference in ctn match value = '046677é464486' VS '046677�464486'

What confuses me is that when I then use the '046677�464486' value and use it in the Postman query I DO get a valid response (the empty one) from my Magento instance.

Is there something we are doing wrong or is there an issue that has to be resolved in order for this to be supported?

#### Platform and Version

AEM: 6.4.5.0
com.adobe.commerce.cif.graphql-client: 1.2.0

**Comment by cjelger** [comment]
I can reproduce the issue with version `1.7.0` of the client, it only happens when using POST to send queries, but works when the client is configured to use GET. It's probably an encoding issue when the query is added to the POST body.

@Jdruwe The workaround is to configure the client to use GET. You could also try to open a PR to fix this?

**Comment by Jdruwe** [comment]
Thanks for the confirmation, we might change to a GET request in the near future. I'll look into a PR if I find the time.

**Comment by cjelger** [comment]
Will be fixed by https://github.com/adobe/commerce-cif-graphql-client/pull/22
